### PR TITLE
Spark 2.3.1 Support

### PR DESCRIPTION
**Pull request by NJordan72**
This PR makes the changes necessary for Magellan to work with Spark 2.3.1 (#213).  All tests are passing and it has been run lightly in production and there are no obvious negative side effects of the upgrade.

### CODE REVIEW

**Comment by harsha2010** [comment]
LGTM!

**Comment by andrescardenasp** [comment]
Hello! this is the exact problem that i'm facing right now, Thanks a lot for fixing it, I have a question, when it will be available to be downloaded via maven?

How can use it right now?

Thanks in advance for your help!

King regards.

**Comment by NJordan72** [comment]
@andrescardenasp  https://jitpack.io/#harsha2010/magellan

**Comment by andrescardenasp** [comment]
Hey! Thanks a lot for you answer.

I followed the jit pack instructions but there is always an error. 
As it can be seen in the master-SNAPSHOT log: 

> Git error. Retrying.
> Git error. Git clone took longer than 180 s

Please can you help me, how can I solve it?

Thanks in advance.

Kind regards.

**Comment by amaciel81** [comment]
Hi,

Looks like the commit to make it compatible with Spark 2.3.1 (402df2f9514c0df1d80fff4fd1e36381765da6c5) couldn't be built: https://jitpack.io/com/github/harsha2010/magellan/402df2f951/build.log

**Comment by smaley07** [comment]
@amaciel81 Indeed, cannot grab the jar for jitpack, did you find an alternative ?

**Comment by andrestobelem** [comment]
how can I get this jar file?

**Pull request merged**
