### PR TITLE
Spatial Join Optimization

### PR DESCRIPTION
**Pull request by harsha2010**
1. Use Broadcast Cartesian Join (eventually replace with Spatial indices?)
2. Avoid type serialization by defining geometric data structures directly as Data Types in Spark SQL.

### CODE REVIEW

**Comment by JoshRosen** [comment]
It seems like the BroadcastCartesianJoin planner rule and physical operators are very similar to Spark's own BroadcastNestedLoopJoin (https://github.com/apache/spark/blob/branch-1.4/sql/core/src/main/scala/org/apache/spark/sql/execution/SparkStrategies.scala#L179). What was the motivation for adding them here vs. changing the relative ordering of the existing `BroadcastNestedLoopJoin ` and `CartesianProduct` rules in the planner?

**Comment by JoshRosen** [comment]
Also, is the intention that users will use a MagellanContext when using Magellan? If so, should the existing examples be updated to reflect this? Right now, I don't see any user-facing examples of MagellanContext usage.

**Comment by harsha2010** [comment]
Hey ideally we shouldn't need Magellan context.. If I can simply plug in to the existing sqlcontext that should be fine... But what I need is the ability to put certain optimization ahead of the standard joins

**Comment by harsha2010** [comment]
Broadcast nested loop join seems to do more.. It seemed slower but I haven't tried it recently.., is there a simple way to put a strategy ahead of all others ?

**Comment by JoshRosen** [comment]
Ah, gotcha. I'd like to discuss whether we can improve Spark's planning / execution support so that this particular optimization can be performed automatically; let's discuss more next week.

BTW, we don't have an API for the re-ordering specifically; just was curious about the reason for a custom rule vs. re-ordering / re-using existing ones.

**Pull request merged**
