### PR TITLE
Fix match error with geometries with numbers without decimal points.

### PR DESCRIPTION
**Pull request by lagerspetz**

### CODE REVIEW

**Comment by lagerspetz** [comment]
Added test data for this.

[intdata-test.geojson.txt](https://github.com/harsha2010/magellan/files/920652/intdata-test.geojson.txt)

**Comment by harsha2010** [comment]
@lagerspetz looks good. can you add a test for the cases (int, double), (int, int) and (double, int) ? i'll merge it in once the tests are covered

**Comment by lagerspetz** [comment]
I also discovered that Points were being read using a different method without matching, so they would also fail with Int data. Now all geometries pass through coordinatesToPoint which handles all of the possible cases. Tests added.

**Comment by harsha2010** [comment]
@lagerspetz thanks a lot for fixing the bugs!

**Pull request merged**
