### PR TITLE
[WIP] initial OSM reader

### PR DESCRIPTION
**Pull request by JasonMWhite**
Definitely not yet complete, but successfully reading data out of the XML file at this point.

Todo:
- merge nodes into ways, ways into relations
- convert everything properly to Point, Line, Polygons, etc
- further investigation of OSM format to see what I've missed

### CODE REVIEW

**Comment by JasonMWhite** [comment]
Sorry 'bout that, finger slipped and picked the wrong repo to PR into :)

**Comment by harsha2010** [comment]
@JasonMWhite , this would make a great PR for Magellan. Care to open one?

**Comment by JasonMWhite** [comment]
I definitely will. I'm probably a ways away from there yet. :)

**Comment by harsha2010** [comment]
sounds good. let me know when you'd like me to review. and thanks for
working on this, this will be a very cool contribution!

**Pull request closed without merging**
